### ISSUE TITLE
Silence the `No "<rule_name>" warnings are being reported` if esplint is run on a subset of files

### ISSUE THREAD

**Issue by moimael** [hjylewis/esplint#142]
Hi,

When running `esplint` for the first time, we create the lockfile based on the defined `surfaceArea`. This works as intended.

But we run `esplint` on a PR, we only want to run it on the files touched by the PR. This works well, except that `esplint` will output a lot of warnings like `No "<rule_name>" warnings are being reported. You can turn it on as an error!`. This makes sense since the PR will not infringe all the watched rules. 

Could we silence those warnings if `esplint` is run with a set of files different from the `surfaceArea`?

Thanks!

**Comment by hjylewis** [comment]
The expected behavior is this:

Even when you run `esplint` on a subset of the `surfaceArea`, it is still using the `.esplint.rec.json` file to check if there are any remaining warnings for `<rule_name>` across all of `surfaceArea`.

It should only report `No "<rule_name>" warnings are being reported. You can turn it on as an error!` when there are no warnings across all of `surfaceArea` even when you are only running `esplint` on a subset of `surfaceArea`.

---

Now there might be a bug. Can you check to make sure that you are seeing `<rule_name>` warnings in your `surfaceArea`? Can you create a mock repo that reproduces this issue?

**Comment by moimael** [comment]
> The expected behavior is this:
> 
> Even when you run `esplint` on a subset of the `surfaceArea`, it is still using the `.esplint.rec.json` file to check if there are any remaining warnings for `<rule_name>` across all of `surfaceArea`.
> 
> It should only report `No "<rule_name>" warnings are being reported. You can turn it on as an error!` when there are no warnings across all of `surfaceArea` even when you are only running `esplint` on a subset of `surfaceArea`.
> 
> Now there might be a bug. Can you check to make sure that you are seeing `<rule_name>` warnings in your `surfaceArea`? Can you create a mock repo that reproduces this issue?

Thanks, it might be a bug then.

I'm definitely not seeing those warning when esplint is run on the surfaceArea. I'll try to create a minimal repro.

**Comment by moimael** [comment]
Seems to have resolved itself, closing.
