### ISSUE TITLE
New rule added while a previous rule is throwing errors.

### ISSUE THREAD

**Issue by umar-muneer** [hjylewis/esplint#76]
So here is the scenario.

Let's say i have a previously defined rule in the config file, "rule1"; it is now throwing errors because a developer increased the number of warnings.

In the same PR, the developer also adds another rule to the config file, "rule2". Now the cli will prompt to use the overwrite flag since the previous record was created with a different configuration. Once the overwrite flag is used, a new record file will be generated disregarding the errors thrown by rule1. Ideally, esplint should still throw error because of rule1 to fail any potential CI build.

**Comment by hjylewis** [comment]
This scenario makes sense. Not sure the best way to solve this is. I'm open to ideas.

The problem is when the eslint config changes, it's easier to completely recreate the record file from scratch. otherwise, the results might not make sense and be confusing for the user.

There is always a risk whenever you use `--overwrite`, new warnings can slip through if you are paying attention. You should probably try not to group too many changes together when you use `--overwrite` otherwise things will slip through.

Hopefully, this is an edge case and someone isn't changing their eslint config enough for this to be big problem.
