### ISSUE TITLE
it looks like esplint silently swallows warnings that are not being tracked

### ISSUE THREAD

**Issue by jasongornall** [hjylewis/esplint#93]
Can we still have them display? How does a dev know if they introduced a new one?

side note: This tool is amazing!

**Comment by hjylewis** [comment]
Thanks for using esplint! 

What's your usecase? Are you adding eslint warnings and realizing later that you weren't tracking them?

Would it be helpful to configure esplint to track all warnings without having to explicitly list them?

Right now there are a couple of reasons we explicitly list out the rules to track
1. this way we can alert the user when that rule nets zero warnings and [they can turn it on as an error.](https://github.com/hjylewis/esplint/blob/bc196cbeeeb3e2e9c08caac2c3fbbe6d24252d8e/lib/ruleSet.js#L58) 
2. if a user adds a warning to eslint, esplint doesn't automatically start throwing errors because of new violations. instead the user must change the configuration and overwrite their existing record files.
3. users have the control to ignore certain rules

There might be ways of gettings these benefits while also allowing a user to track all warnings automatically.

---

I'm wondering if a configuration like this would work for your usecase
```json
{
  "rules": [ "*" ],
}
```

**Comment by jasongornall** [comment]
So essentially we have a VERY large codebase and any introduction of a brand new warning (what happened) seems to fly under the radar

1: we don't even know it is introduced
2: we think everything is all good.

I actually think ` "rules": [ "*" ],` would help us out a ton! This would prevent the use-case I'm seeing.

**Comment by hjylewis** [comment]
Gotcha. Thanks for the feedback!

I think something you can put in place in the meantime if your eslint config is simple would be dynamically grabbing the list of rules from your eslint config.

```js
// .esplintrc.js
const eslintConfig = require('./.eslintrc');
const rules = Object.keys(eslintConfig.rules).filter(rule => {
  const ruleConfig = eslintConfig.rules[rule];
  const ruleValue = Array.isArray(ruleConfig) ? ruleConfig[0] : ruleConfig;
  return ruleValue === 'warn';
});

module.exports = {
  surfaceArea: ["."],
  rules: rules,
};
```

**Comment by jasongornall** [comment]
This solution worked perfectly for our use-case! Thankyou!

**Comment by hjylewis** [comment]
Wonderful! Thanks for using esplint.

Closing this for now. If someone comes along and [this solution](https://github.com/hjylewis/esplint/issues/93#issuecomment-723476365) does not work, feel free to re-open this issue with details.
